# Generated by Django 3.2.5 on 2021-08-16 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orders_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='item_json',
            new_name='itemJson',
        ),
    ]
