# Generated by Django 3.2.5 on 2021-08-16 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_item_json_orders_itemjson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='itemJson',
            new_name='itemsJson',
        ),
    ]
