# Generated by Django 3.2.5 on 2021-08-16 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_itemjson_orders_itemsjson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='itemsJson',
            new_name='items_json',
        ),
    ]
